[tool.poetry]
name = "dj-htmx"
version = "0.1.0"
description = ""
authors = ["Ning <a24701770@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1"
psycopg = "^3.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
