# Generated by Django 5.1 on 2024-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Progressing', 'Progressing')], default='Progressing', max_length=15),
        ),
    ]
